name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt --check